color:
  saturation: 0.942445
  brandStrength: 0.6308244
  rhythmicContrast: 0.7259808
  brandColors:
    - '#161614'
    - '#454464'
    - '#C3AD88'
    - '#8A7E66'
    - '#D7CBB5'
  lightness: 0.04340412
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
layout_spectrum: 0
typography_spectrum: 0.218638
name: CocoPibble
